In [1]:
import random

In [14]:
random.random()

0.16684776123962297

In [15]:
import torch

In [16]:
a = torch.arange(24).reshape(3, 2, 4)

In [120]:
a = torch.tensor([1, 1, 1, 0, 0, 1])

In [121]:
a = a.unsqueeze(0)

In [122]:
a @ a.T

tensor([[4]])

In [123]:
a.T @ a

tensor([[1, 1, 1, 0, 0, 1],
        [1, 1, 1, 0, 0, 1],
        [1, 1, 1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 1]])

In [124]:
a

tensor([[1, 1, 1, 0, 0, 1]])

In [125]:
torch.stack([a])

tensor([[[1, 1, 1, 0, 0, 1]]])

In [64]:
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [71]:
a = (torch.randn(2, 3, 4) * 10).to(int)

In [72]:
a

tensor([[[  4,  -2,   0,   5],
         [  8,  -9,  -2,  -4],
         [  7,  10,  -3,   1]],

        [[-11,  14,  17,  14],
         [  7,  -7,  -1,  26],
         [ -8,  14,   0,  19]]])

In [73]:
torch.sort(a, dim=-1)

torch.return_types.sort(
values=tensor([[[ -2,   0,   4,   5],
         [ -9,  -4,  -2,   8],
         [ -3,   1,   7,  10]],

        [[-11,  14,  14,  17],
         [ -7,  -1,   7,  26],
         [ -8,   0,  14,  19]]]),
indices=tensor([[[1, 2, 0, 3],
         [1, 3, 2, 0],
         [2, 3, 0, 1]],

        [[0, 1, 3, 2],
         [1, 2, 0, 3],
         [0, 2, 1, 3]]]))

In [75]:
a = [torch.tensor([1])] * 3

In [77]:
b = torch.tensor(1)

In [78]:
b

tensor(1)

In [79]:
b in a

True

In [80]:
1 in a

True

In [81]:
a

[tensor([1]), tensor([1]), tensor([1])]

In [82]:
set(a)

{tensor([1])}

In [83]:
b = torch.tensor([[1, 2, 3, 2], [4,2,3,4]])

In [86]:
set(b[1].tolist())

{2, 3, 4}

In [88]:
set([0])

{0}

In [5]:
from datetime import datetime

In [12]:
datetime.strftime(datetime.now(), '%Y.%m.%d %H:%M:%S')

'2024.04.21 08:59:54'

In [92]:
a[-1].extend(random.sample(set([5,65,7]), 3))

/var/folders/6g/83bk7w6d5nlbhh_5lzmncb0m0000gn/T/ipykernel_18896/400862352.py:1: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  a[-1].extend(random.sample(set([5,65,7]), 3))


In [93]:
a

[[4, 5], [9, 5, 65, 7, 7, 65, 5]]

In [95]:
random.sample(list(set(range(9))), 3)

[4, 5, 7]

In [96]:
s = set([4,5,6])

In [14]:
import torch

In [19]:
a = torch.arange(24).view(2,3,4)

In [24]:
a.unbind(-1)

(tensor([[ 0,  4,  8],
         [12, 16, 20]]),
 tensor([[ 1,  5,  9],
         [13, 17, 21]]),
 tensor([[ 2,  6, 10],
         [14, 18, 22]]),
 tensor([[ 3,  7, 11],
         [15, 19, 23]]))

In [23]:
torch.unbind(a, 2)

(tensor([[ 0,  4,  8],
         [12, 16, 20]]),
 tensor([[ 1,  5,  9],
         [13, 17, 21]]),
 tensor([[ 2,  6, 10],
         [14, 18, 22]]),
 tensor([[ 3,  7, 11],
         [15, 19, 23]]))

In [25]:
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [26]:
b = torch.arange(4, 28).view(2, 3, 4)

In [27]:
b

tensor([[[ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27]]])

In [28]:
torch.max(a, b)

tensor([[[ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27]]])

In [34]:
torch.max(a, torch.ones_like(a))

tensor([[[ 1,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [35]:
a.shape

torch.Size([2, 3, 4])

In [37]:
a.unbind(-1)[0].shape

torch.Size([2, 3])

In [39]:
torch.tensor([True, False]).sum()

tensor(1)

In [40]:
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [42]:
a = torch.rand(6)

In [43]:
a

tensor([0.4995, 0.8259, 0.1623, 0.2780, 0.3610, 0.2912])

In [44]:
a.dtype

torch.float32

In [45]:
random.random(9)

NameError: name 'random' is not defined

In [46]:
import random

In [56]:
random.randint(4,4)

4